### ISSUE TITLE
Navigation bar with responsive menu

### ISSUE THREAD

**Issue by Apollo10101** [HymaJujjuru/CSCI3308-Project-Group014-4#1]
As a user, I should be able to see the available pages on an interactive nav bar and be redirected to those pages when I click on them.

Acceptance Criteria: Buttons are clearly visible to the user and redirect the user to the specified page when the user clicks on a button.

**Comment by HymaJujjuru** [comment]
As a user, I should be able to see the available pages on an interactive nav bar and be redirected to those pages when I click on them.
